# coding: utf-8


from PyQt5 import QtCore, QtWidgets


class Ui_MakeTag(object):
    def setupUi(self, MakeTag):
        MakeTag.setObjectName("MakeTag")
        MakeTag.resize(751, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MakeTag.sizePolicy().hasHeightForWidth())
        MakeTag.setSizePolicy(sizePolicy)
        MakeTag.setMinimumSize(QtCore.QSize(751, 607))
        MakeTag.setMaximumSize(QtCore.QSize(751, 607))
        MakeTag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget = QtWidgets.QWidget(MakeTag)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(751, 600))
        self.centralWidget.setMaximumSize(QtCore.QSize(751, 600))
        self.centralWidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralWidget.setMouseTracking(True)
        self.centralWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget.setAutoFillBackground(True)
        self.centralWidget.setObjectName("centralWidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 190, 401, 301))
        self.textBrowser.setSizeIncrement(QtCore.QSize(0, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 510, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(684, 50, 61, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(240, 10, 441, 111))
        self.listWidget.setObjectName("listWidget")
        self.verticalWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalWidget.setGeometry(QtCore.QRect(450, 180, 271, 331))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.verticalWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.horizontalLayout_3.addWidget(self.textBrowser_1)
        self.radioButton_1pos = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1pos.setObjectName("radioButton_1pos")
        self.horizontalLayout_3.addWidget(self.radioButton_1pos)
        self.radioButton_1none = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1none.setChecked(True)
        self.radioButton_1none.setObjectName("radioButton_1none")
        self.horizontalLayout_3.addWidget(self.radioButton_1none)
        self.radioButton_1neg = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1neg.setObjectName("radioButton_1neg")
        self.horizontalLayout_3.addWidget(self.radioButton_1neg)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget(self.verticalWidget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_8.addWidget(self.textBrowser_2)
        self.radioButton_2pos = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2pos.setObjectName("radioButton_2pos")
        self.horizontalLayout_8.addWidget(self.radioButton_2pos)
        self.radioButton_2none = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2none.setChecked(True)
        self.radioButton_2none.setObjectName("radioButton_2none")
        self.horizontalLayout_8.addWidget(self.radioButton_2none)
        self.radioButton_2neg = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2neg.setObjectName("radioButton_2neg")
        self.horizontalLayout_8.addWidget(self.radioButton_2neg)
        self.verticalLayout_2.addWidget(self.widget1)
        self.widget2 = QtWidgets.QWidget(self.verticalWidget)
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget2)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_7.addWidget(self.textBrowser_3)
        self.radioButton_3pos = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3pos.setObjectName("radioButton_3pos")
        self.horizontalLayout_7.addWidget(self.radioButton_3pos)
        self.radioButton_3none = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3none.setChecked(True)
        self.radioButton_3none.setObjectName("radioButton_3none")
        self.horizontalLayout_7.addWidget(self.radioButton_3none)
        self.radioButton_3neg = QtWidgets.QRadioButton(self.widget2)
        self.radioButton_3neg.setObjectName("radioButton_3neg")
        self.horizontalLayout_7.addWidget(self.radioButton_3neg)
        self.verticalLayout_2.addWidget(self.widget2)
        self.widget3 = QtWidgets.QWidget(self.verticalWidget)
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget3)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.horizontalLayout_6.addWidget(self.textBrowser_4)
        self.radioButton_4pos = QtWidgets.QRadioButton(self.widget3)
        self.radioButton_4pos.setObjectName("radioButton_4pos")
        self.horizontalLayout_6.addWidget(self.radioButton_4pos)
        self.radioButton_4none = QtWidgets.QRadioButton(self.widget3)
        self.radioButton_4none.setChecked(True)
        self.radioButton_4none.setObjectName("radioButton_4none")
        self.horizontalLayout_6.addWidget(self.radioButton_4none)
        self.radioButton_4neg = QtWidgets.QRadioButton(self.widget3)
        self.radioButton_4neg.setObjectName("radioButton_4neg")
        self.horizontalLayout_6.addWidget(self.radioButton_4neg)
        self.verticalLayout_2.addWidget(self.widget3)
        self.widget4 = QtWidgets.QWidget(self.verticalWidget)
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.widget4)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.horizontalLayout_5.addWidget(self.textBrowser_5)
        self.radioButton_5pos = QtWidgets.QRadioButton(self.widget4)
        self.radioButton_5pos.setObjectName("radioButton_5pos")
        self.horizontalLayout_5.addWidget(self.radioButton_5pos)
        self.radioButton_5none = QtWidgets.QRadioButton(self.widget4)
        self.radioButton_5none.setChecked(True)
        self.radioButton_5none.setObjectName("radioButton_5none")
        self.horizontalLayout_5.addWidget(self.radioButton_5none)
        self.radioButton_5neg = QtWidgets.QRadioButton(self.widget4)
        self.radioButton_5neg.setObjectName("radioButton_5neg")
        self.horizontalLayout_5.addWidget(self.radioButton_5neg)
        self.verticalLayout_2.addWidget(self.widget4)
        self.widget5 = QtWidgets.QWidget(self.verticalWidget)
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.widget5)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_4.addWidget(self.textBrowser_6)
        self.radioButton_6pos = QtWidgets.QRadioButton(self.widget5)
        self.radioButton_6pos.setObjectName("radioButton_6pos")
        self.horizontalLayout_4.addWidget(self.radioButton_6pos)
        self.radioButton_6none = QtWidgets.QRadioButton(self.widget5)
        self.radioButton_6none.setChecked(True)
        self.radioButton_6none.setObjectName("radioButton_6none")
        self.horizontalLayout_4.addWidget(self.radioButton_6none)
        self.radioButton_6neg = QtWidgets.QRadioButton(self.widget5)
        self.radioButton_6neg.setObjectName("radioButton_6neg")
        self.horizontalLayout_4.addWidget(self.radioButton_6neg)
        self.verticalLayout_2.addWidget(self.widget5)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 191, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 51, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(470, 160, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 201, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(240, 160, 71, 16))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 500, 281, 31))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.label_product = QtWidgets.QLabel(self.centralWidget)
        self.label_product.setGeometry(QtCore.QRect(300, 130, 201, 16))
        self.label_product.setObjectName("label_product")
        self.label_all = QtWidgets.QLabel(self.centralWidget)
        self.label_all.setGeometry(QtCore.QRect(370, 510, 71, 16))
        self.label_all.setObjectName("label_all")
        self.label_tagged = QtWidgets.QLabel(self.centralWidget)
        self.label_tagged.setGeometry(QtCore.QRect(280, 510, 91, 16))
        self.label_tagged.setObjectName("label_tagged")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 510, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalWidget.raise_()
        self.textBrowser.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.listWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.checkBox.raise_()
        self.label_5.raise_()
        self.label_product.raise_()
        self.label_all.raise_()
        self.label_tagged.raise_()
        self.pushButton_3.raise_()
        MakeTag.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MakeTag)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 751, 24))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MakeTag.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MakeTag)
        self.mainToolBar.setObjectName("mainToolBar")
        MakeTag.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MakeTag)
        self.statusBar.setObjectName("statusBar")
        MakeTag.setStatusBar(self.statusBar)
        self.actionFihish = QtWidgets.QAction(MakeTag)
        self.actionFihish.setObjectName("actionFihish")
        self.menu.addAction(self.actionFihish)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MakeTag)
        QtCore.QMetaObject.connectSlotsByName(MakeTag)

    def retranslateUi(self, MakeTag):
        _translate = QtCore.QCoreApplication.translate
        MakeTag.setWindowTitle(_translate("MakeTag", "MakeTag"))
        self.pushButton.setText(_translate("MakeTag", "次へ"))
        self.pushButton_2.setText(_translate("MakeTag", "決定"))
        self.pushButton_3.setText(_translate("MakeTag", "Dropout"))
        self.radioButton_1pos.setText(_translate("MakeTag", "pos"))
        self.radioButton_1none.setText(_translate("MakeTag", "none"))
        self.radioButton_1neg.setText(_translate("MakeTag", "neg"))
        self.radioButton_2pos.setText(_translate("MakeTag", "pos"))
        self.radioButton_2none.setText(_translate("MakeTag", "none"))
        self.radioButton_2neg.setText(_translate("MakeTag", "neg"))
        self.radioButton_3pos.setText(_translate("MakeTag", "pos"))
        self.radioButton_3none.setText(_translate("MakeTag", "none"))
        self.radioButton_3neg.setText(_translate("MakeTag", "neg"))
        self.radioButton_4pos.setText(_translate("MakeTag", "pos"))
        self.radioButton_4none.setText(_translate("MakeTag", "none"))
        self.radioButton_4neg.setText(_translate("MakeTag", "neg"))
        self.radioButton_5pos.setText(_translate("MakeTag", "pos"))
        self.radioButton_5none.setText(_translate("MakeTag", "none"))
        self.radioButton_5neg.setText(_translate("MakeTag", "neg"))
        self.radioButton_6pos.setText(_translate("MakeTag", "pos"))
        self.radioButton_6none.setText(_translate("MakeTag", "none"))
        self.radioButton_6neg.setText(_translate("MakeTag", "neg"))
        self.label.setText(_translate("MakeTag", "<html><head/><body><p><span style=\" font-size:11pt;\">ＤＢ：</span></p></body></html>"))
        self.label_2.setText(_translate("MakeTag", "<html><head/><body><p><span style=\" font-size:14pt;\">本文</span></p></body></html>"))
        self.label_3.setText(_translate("MakeTag", "<html><head/><body><p><span style=\" font-size:14pt;\">属性</span></p></body></html>"))
        self.label_4.setText(_translate("MakeTag", "<html><head/><body><p><span style=\" font-size:11pt;\">Collection:</span></p></body></html>"))
        self.checkBox.setText(_translate("MakeTag", "ラベル付されていないもののみ表示"))
        self.label_5.setText(_translate("MakeTag", "評価："))
        self.label_product.setText(_translate("MakeTag", "selected: None"))
        self.label_all.setText(_translate("MakeTag", "総数:"))
        self.label_tagged.setText(_translate("MakeTag", "済:"))
        self.menu.setTitle(_translate("MakeTag", "タグ付けツール"))
        self.actionFihish.setText(_translate("MakeTag", "exit"))
